### ISSUE TITLE
Doesn’t work.

### ISSUE THREAD

**Issue by italianjesus** [xakeplusplus/OwOAutoGrinder#4]
No matter what I do, it just doesn’t work. A little guide would be nice.

**Comment by xakeplusplus** [comment]
fine, i would make a guide

**Comment by xakeplusplus** [comment]
i updated the README.md there should be a guide now

**Comment by xakeplusplus** [comment]
Also make sure that ur using the main branch and not the experimental. Cuz the experimental branch doesn't work i think
