### ISSUE TITLE
It doesn’t run 

### ISSUE THREAD

**Issue by italianjesus** [xakeplusplus/OwOAutoGrinder#6]
After the update, it doesnt run for a reason. I don’t know why :/

**Comment by xakeplusplus** [comment]
can you try running it from cmd. Copy destination to the folder where your main.py file is at. Open cmd. Now type python main.py or python3 main.py try both. Send the thing it says here.

can you try doing ```pip3 install discord``` or ```pip install discord``` and try running the thing afterwards see if it works

**Comment by xakeplusplus** [comment]
maybe u forgot to put ur token in?
