### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ill02** [xakeplusplus/OwOAutoGrinder#7]
#from discord import channel, message
^

SyntaxError: Private field '#from' must be declared in an enclosing class
←[90m    at Object.compileFunction (node:vm:352:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1031:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1065:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m

**Comment by xakeplusplus** [comment]
Sry. I didn't see the issue. Notification just came up to me. I'll see what can i do.

**Comment by xakeplusplus** [comment]
try now
